### ISSUE TITLE
JSON Decode Error with Bad Token

### ISSUE THREAD

**Issue by jamesmunns** [relayr/python-sdk#31]
When attempting to use a bad token to create a `Client` object, the error request is not handled correctly, leading to an unhelpful exception being thrown. Here is an example that causes this:

```python
from relayr import Client
client = Client(token="badtoken")
user = client.get_user()
```

Result:
```
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    user = client.get_user()
  File "/Users/jamesmunns/test_api/python-sdk/relayr/client.py", line 141, in get_user
    info = self.api.get_oauth2_user_info()
  File "/Users/jamesmunns/test_api/python-sdk/relayr/api.py", line 352, in get_oauth2_user_info
    _, data = self.perform_request('GET', url, headers=self.headers)
  File "/Users/jamesmunns/test_api/python-sdk/relayr/api.py", line 185, in perform_request
    args = (resp.json()['message'], method.upper(), url)
  File "/Users/jamesmunns/test_api/python-sdk/venv/lib/python3.5/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jamesmunns** [comment]
Workaround: If you see an error like this, please verify your token is correct.
